const elements = [
    /* PERIOD 1 */
    { number: 1, symbol: "H", name: "Hydrogen", category: "nonmetal", col: 1, row: 1, desc: "Lightest element.", uses: "Fuel, ammonia.", pros: "Clean fuel.", cons: "Explosive." },
    { number: 2, symbol: "He", name: "Helium", category: "noble gas", col: 18, row: 1, desc: "Inert gas.", uses: "Cooling, balloons.", pros: "Stable.", cons: "Scarce." },

    /* PERIOD 2 */
    { number: 3, symbol: "Li", name: "Lithium", category: "alkali metal", col: 1, row: 2, desc: "Soft metal.", uses: "Batteries.", pros: "High energy.", cons: "Reactive." },
    { number: 4, symbol: "Be", name: "Beryllium", category: "alkaline earth metal", col: 2, row: 2, desc: "Light metal.", uses: "Aerospace.", pros: "Strong.", cons: "Toxic." },
    { number: 5, symbol: "B", name: "Boron", category: "metalloid", col: 13, row: 2, desc: "Semi-metal.", uses: "Glass.", pros: "Heat resistant.", cons: "Brittle." },
    { number: 6, symbol: "C", name: "Carbon", category: "nonmetal", col: 14, row: 2, desc: "Basis of life.", uses: "Fuel, steel.", pros: "Versatile.", cons: "CO₂." },
    { number: 7, symbol: "N", name: "Nitrogen", category: "nonmetal", col: 15, row: 2, desc: "Air gas.", uses: "Fertilizer.", pros: "Stable.", cons: "Needs fixing." },
    { number: 8, symbol: "O", name: "Oxygen", category: "nonmetal", col: 16, row: 2, desc: "Supports life.", uses: "Medical.", pros: "Essential.", cons: "Oxidation." },
    { number: 9, symbol: "F", name: "Fluorine", category: "halogen", col: 17, row: 2, desc: "Highly reactive.", uses: "Toothpaste.", pros: "Useful.", cons: "Toxic." },
    { number: 10, symbol: "Ne", name: "Neon", category: "noble gas", col: 18, row: 2, desc: "Noble gas.", uses: "Lighting.", pros: "Stable.", cons: "Rare." },

    /* PERIOD 3 */
    { number: 11, symbol: "Na", name: "Sodium", category: "alkali metal", col: 1, row: 3, desc: "Soft metal.", uses: "Salt.", pros: "Useful.", cons: "Reacts." },
    { number: 12, symbol: "Mg", name: "Magnesium", category: "alkaline earth metal", col: 2, row: 3, desc: "Light metal.", uses: "Alloys.", pros: "Strong.", cons: "Burns." },
    { number: 13, symbol: "Al", name: "Aluminium", category: "post-transition metal", col: 13, row: 3, desc: "Light metal.", uses: "Construction.", pros: "Resistant.", cons: "Energy cost." },
    { number: 14, symbol: "Si", name: "Silicon", category: "metalloid", col: 14, row: 3, desc: "Semiconductor.", uses: "Electronics.", pros: "Key tech.", cons: "Brittle." },
    { number: 15, symbol: "P", name: "Phosphorus", category: "nonmetal", col: 15, row: 3, desc: "Reactive.", uses: "Fertilizer.", pros: "Essential.", cons: "Toxic forms." },
    { number: 16, symbol: "S", name: "Sulfur", category: "nonmetal", col: 16, row: 3, desc: "Yellow solid.", uses: "Acid.", pros: "Industrial.", cons: "Toxic gas." },
    { number: 17, symbol: "Cl", name: "Chlorine", category: "halogen", col: 17, row: 3, desc: "Green gas.", uses: "Water.", pros: "Kills germs.", cons: "Toxic." },
    { number: 18, symbol: "Ar", name: "Argon", category: "noble gas", col: 18, row: 3, desc: "Inert.", uses: "Welding.", pros: "Stable.", cons: "Limited." },

    /* PERIOD 4 */
    { number: 19, symbol: "K", name: "Potassium", category: "alkali metal", col: 1, row: 4, desc: "Reactive.", uses: "Fertilizer.", pros: "Essential.", cons: "Violent." },
    { number: 20, symbol: "Ca", name: "Calcium", category: "alkaline earth metal", col: 2, row: 4, desc: "Bone element.", uses: "Cement.", pros: "Strong.", cons: "Reactive." },
    { number: 21, symbol: "Sc", name: "Scandium", category: "transition metal", col: 3, row: 4, desc: "Rare metal.", uses: "Alloys.", pros: "Light.", cons: "Costly." },
    { number: 22, symbol: "Ti", name: "Titanium", category: "transition metal", col: 4, row: 4, desc: "Strong metal.", uses: "Aerospace.", pros: "Corrosion-proof.", cons: "Expensive." },
    { number: 23, symbol: "V", name: "Vanadium", category: "transition metal", col: 5, row: 4, desc: "Hard metal.", uses: "Steel.", pros: "Strength.", cons: "Toxic dust." },
    { number: 24, symbol: "Cr", name: "Chromium", category: "transition metal", col: 6, row: 4, desc: "Shiny metal.", uses: "Plating.", pros: "Resistant.", cons: "Toxic forms." },
    { number: 25, symbol: "Mn", name: "Manganese", category: "transition metal", col: 7, row: 4, desc: "Brittle metal.", uses: "Steel.", pros: "Hardness.", cons: "Toxic." },
    { number: 26, symbol: "Fe", name: "Iron", category: "transition metal", col: 8, row: 4, desc: "Common metal.", uses: "Construction.", pros: "Strong.", cons: "Rusts." },
    { number: 27, symbol: "Co", name: "Cobalt", category: "transition metal", col: 9, row: 4, desc: "Magnetic.", uses: "Batteries.", pros: "Stable.", cons: "Toxic." },
    { number: 28, symbol: "Ni", name: "Nickel", category: "transition metal", col: 10, row: 4, desc: "Resistant.", uses: "Alloys.", pros: "Durable.", cons: "Allergy." },
    { number: 29, symbol: "Cu", name: "Copper", category: "transition metal", col: 11, row: 4, desc: "Conductive.", uses: "Wires.", pros: "Excellent conductor.", cons: "Oxidizes." },
    { number: 30, symbol: "Zn", name: "Zinc", category: "transition metal", col: 12, row: 4, desc: "Protective metal.", uses: "Galvanizing.", pros: "Prevents rust.", cons: "Brittle." },
    { number: 31, symbol: "Ga", name: "Gallium", category: "post-transition metal", col: 13, row: 4, desc: "Low-melting.", uses: "Electronics.", pros: "Semiconductor.", cons: "Soft." },
    { number: 32, symbol: "Ge", name: "Germanium", category: "metalloid", col: 14, row: 4, desc: "Semiconductor.", uses: "Fiber optics.", pros: "Efficient.", cons: "Costly." },
    { number: 33, symbol: "As", name: "Arsenic", category: "metalloid", col: 15, row: 4, desc: "Toxic.", uses: "Semiconductors.", pros: "Useful.", cons: "Poison." },
    { number: 34, symbol: "Se", name: "Selenium", category: "nonmetal", col: 16, row: 4, desc: "Photoconductive.", uses: "Glass.", pros: "Useful.", cons: "Toxic." },
    { number: 35, symbol: "Br", name: "Bromine", category: "halogen", col: 17, row: 4, desc: "Liquid nonmetal.", uses: "Flame retardants.", pros: "Reactive.", cons: "Toxic." },
    { number: 36, symbol: "Kr", name: "Krypton", category: "noble gas", col: 18, row: 4, desc: "Noble gas.", uses: "Lighting.", pros: "Stable.", cons: "Rare." },

    /* PERIOD 5 */
    { number: 37, symbol: "Rb", name: "Rubidium", category: "alkali metal", col: 1, row: 5, desc: "Very reactive.", uses: "Research.", pros: "Reactive.", cons: "Dangerous." },
    { number: 38, symbol: "Sr", name: "Strontium", category: "alkaline earth metal", col: 2, row: 5, desc: "Soft metal.", uses: "Fireworks.", pros: "Bright red.", cons: "Reactive." },
    { number: 39, symbol: "Y", name: "Yttrium", category: "transition metal", col: 3, row: 5, desc: "Rare earth.", uses: "LEDs.", pros: "Useful.", cons: "Cost." },
    { number: 40, symbol: "Zr", name: "Zirconium", category: "transition metal", col: 4, row: 5, desc: "Corrosion resistant.", uses: "Nuclear.", pros: "Stable.", cons: "Cost." },
    { number: 41, symbol: "Nb", name: "Niobium", category: "transition metal", col: 5, row: 5, desc: "Ductile.", uses: "Alloys.", pros: "Strength.", cons: "Rare." },
    { number: 42, symbol: "Mo", name: "Molybdenum", category: "transition metal", col: 6, row: 5, desc: "High-temp.", uses: "Steel.", pros: "Strong.", cons: "Cost." },
    { number: 43, symbol: "Tc", name: "Technetium", category: "transition metal", col: 7, row: 5, desc: "Radioactive.", uses: "Medical imaging.", pros: "Useful.", cons: "Radioactive." },
    { number: 44, symbol: "Ru", name: "Ruthenium", category: "transition metal", col: 8, row: 5, desc: "Hard metal.", uses: "Electronics.", pros: "Durable.", cons: "Rare." },
    { number: 45, symbol: "Rh", name: "Rhodium", category: "transition metal", col: 9, row: 5, desc: "Reflective.", uses: "Catalysts.", pros: "Resistant.", cons: "Expensive." },
    { number: 46, symbol: "Pd", name: "Palladium", category: "transition metal", col: 10, row: 5, desc: "Absorbs H₂.", uses: "Catalysts.", pros: "Useful.", cons: "Cost." },
    { number: 47, symbol: "Ag", name: "Silver", category: "transition metal", col: 11, row: 5, desc: "Best conductor.", uses: "Jewelry.", pros: "Conductive.", cons: "Tarnish." },
    { number: 48, symbol: "Cd", name: "Cadmium", category: "transition metal", col: 12, row: 5, desc: "Soft toxic.", uses: "Batteries.", pros: "Useful.", cons: "Toxic." },
    { number: 49, symbol: "In", name: "Indium", category: "post-transition metal", col: 13, row: 5, desc: "Soft metal.", uses: "Screens.", pros: "Useful.", cons: "Rare." },
    { number: 50, symbol: "Sn", name: "Tin", category: "post-transition metal", col: 14, row: 5, desc: "Corrosion resistant.", uses: "Coating.", pros: "Safe.", cons: "Weak." },
    { number: 51, symbol: "Sb", name: "Antimony", category: "metalloid", col: 15, row: 5, desc: "Brittle.", uses: "Flame retardants.", pros: "Useful.", cons: "Toxic." },
    { number: 52, symbol: "Te", name: "Tellurium", category: "metalloid", col: 16, row: 5, desc: "Rare.", uses: "Solar.", pros: "Useful.", cons: "Rare." },
    { number: 53, symbol: "I", name: "Iodine", category: "halogen", col: 17, row: 5, desc: "Essential.", uses: "Medicine.", pros: "Vital.", cons: "Toxic in excess." },
    { number: 54, symbol: "Xe", name: "Xenon", category: "noble gas", col: 18, row: 5, desc: "Heavy noble gas.", uses: "Lighting.", pros: "Stable.", cons: "Rare." },

    /* PERIOD 6 */
    { number: 55, symbol: "Cs", name: "Cesium", category: "alkali metal", col: 1, row: 6, desc: "Very reactive.", uses: "Clocks.", pros: "Precise.", cons: "Explosive." },
    { number: 56, symbol: "Ba", name: "Barium", category: "alkaline earth metal", col: 2, row: 6, desc: "Dense.", uses: "Medical imaging.", pros: "Useful.", cons: "Toxic." },
    
    /* LANTHANIDES (Shifted to row 9 for spacing) */
    { number: 57, symbol: "La", name: "Lanthanum", category: "lanthanide", col: 3, row: 9, desc: "Rare earth.", uses: "Lenses.", pros: "Useful.", cons: "Cost." },
    { number: 58, symbol: "Ce", name: "Cerium", category: "lanthanide", col: 4, row: 9, desc: "Reactive.", uses: "Catalysts.", pros: "Useful.", cons: "Oxidizes." },
    { number: 59, symbol: "Pr", name: "Praseodymium", category: "lanthanide", col: 5, row: 9, desc: "Soft.", uses: "Magnets.", pros: "Useful.", cons: "Reactive." },
    { number: 60, symbol: "Nd", name: "Neodymium", category: "lanthanide", col: 6, row: 9, desc: "Magnetic.", uses: "Magnets.", pros: "Strong.", cons: "Corrodes." },
    { number: 61, symbol: "Pm", name: "Promethium", category: "lanthanide", col: 7, row: 9, desc: "Radioactive.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 62, symbol: "Sm", name: "Samarium", category: "lanthanide", col: 8, row: 9, desc: "Magnetic.", uses: "Magnets.", pros: "Stable.", cons: "Brittle." },
    { number: 63, symbol: "Eu", name: "Europium", category: "lanthanide", col: 9, row: 9, desc: "Soft.", uses: "Displays.", pros: "Bright.", cons: "Reactive." },
    { number: 64, symbol: "Gd", name: "Gadolinium", category: "lanthanide", col: 10, row: 9, desc: "Magnetic.", uses: "MRI.", pros: "Useful.", cons: "Cost." },
    { number: 65, symbol: "Tb", name: "Terbium", category: "lanthanide", col: 11, row: 9, desc: "Rare.", uses: "Phosphors.", pros: "Bright.", cons: "Rare." },
    { number: 66, symbol: "Dy", name: "Dysprosium", category: "lanthanide", col: 12, row: 9, desc: "Magnetic.", uses: "Motors.", pros: "Strong.", cons: "Cost." },
    { number: 67, symbol: "Ho", name: "Holmium", category: "lanthanide", col: 13, row: 9, desc: "Magnetic.", uses: "Lasers.", pros: "Useful.", cons: "Rare." },
    { number: 68, symbol: "Er", name: "Erbium", category: "lanthanide", col: 14, row: 9, desc: "Pink salts.", uses: "Fiber optics.", pros: "Useful.", cons: "Cost." },
    { number: 69, symbol: "Tm", name: "Thulium", category: "lanthanide", col: 15, row: 9, desc: "Rare.", uses: "Lasers.", pros: "Useful.", cons: "Rare." },
    { number: 70, symbol: "Yb", name: "Ytterbium", category: "lanthanide", col: 16, row: 9, desc: "Soft.", uses: "Alloys.", pros: "Useful.", cons: "Reactive." },
    { number: 71, symbol: "Lu", name: "Lutetium", category: "lanthanide", col: 17, row: 9, desc: "Dense.", uses: "Catalysts.", pros: "Stable.", cons: "Cost." },

    { number: 72, symbol: "Hf", name: "Hafnium", category: "transition metal", col: 4, row: 6, desc: "High-temp.", uses: "Nuclear.", pros: "Stable.", cons: "Cost." },
    { number: 73, symbol: "Ta", name: "Tantalum", category: "transition metal", col: 5, row: 6, desc: "Corrosion resistant.", uses: "Electronics.", pros: "Durable.", cons: "Cost." },
    { number: 74, symbol: "W", name: "Tungsten", category: "transition metal", col: 6, row: 6, desc: "Very high melting.", uses: "Filaments.", pros: "Heat resistant.", cons: "Brittle." },
    { number: 75, symbol: "Re", name: "Rhenium", category: "transition metal", col: 7, row: 6, desc: "Dense.", uses: "Alloys.", pros: "Durable.", cons: "Rare." },
    { number: 76, symbol: "Os", name: "Osmium", category: "transition metal", col: 8, row: 6, desc: "Very dense.", uses: "Alloys.", pros: "Hard.", cons: "Toxic oxide." },
    { number: 77, symbol: "Ir", name: "Iridium", category: "transition metal", col: 9, row: 6, desc: "Corrosion resistant.", uses: "Contacts.", pros: "Durable.", cons: "Rare." },
    { number: 78, symbol: "Pt", name: "Platinum", category: "transition metal", col: 10, row: 6, desc: "Precious.", uses: "Catalysts.", pros: "Stable.", cons: "Expensive." },
    { number: 79, symbol: "Au", name: "Gold", category: "transition metal", col: 11, row: 6, desc: "Precious.", uses: "Jewelry.", pros: "Non-reactive.", cons: "Cost." },
    { number: 80, symbol: "Hg", name: "Mercury", category: "transition metal", col: 12, row: 6, desc: "Liquid metal.", uses: "Instruments.", pros: "Unique.", cons: "Toxic." },
    { number: 81, symbol: "Tl", name: "Thallium", category: "post-transition metal", col: 13, row: 6, desc: "Soft.", uses: "Electronics.", pros: "Useful.", cons: "Toxic." },
    { number: 82, symbol: "Pb", name: "Lead", category: "post-transition metal", col: 14, row: 6, desc: "Dense.", uses: "Batteries.", pros: "Shielding.", cons: "Toxic." },
    { number: 83, symbol: "Bi", name: "Bismuth", category: "post-transition metal", col: 15, row: 6, desc: "Low toxicity.", uses: "Medicines.", pros: "Safer.", cons: "Brittle." },
    { number: 84, symbol: "Po", name: "Polonium", category: "metalloid", col: 16, row: 6, desc: "Radioactive.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 85, symbol: "At", name: "Astatine", category: "halogen", col: 17, row: 6, desc: "Very rare.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 86, symbol: "Rn", name: "Radon", category: "noble gas", col: 18, row: 6, desc: "Radioactive gas.", uses: "Research.", pros: "Inert.", cons: "Hazard." },

    /* PERIOD 7 */
    { number: 87, symbol: "Fr", name: "Francium", category: "alkali metal", col: 1, row: 7, desc: "Extremely rare.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 88, symbol: "Ra", name: "Radium", category: "alkaline earth metal", col: 2, row: 7, desc: "Radioactive.", uses: "Research.", pros: "Unique.", cons: "Hazard." },
    
    /* ACTINIDES (Shifted to row 10 for spacing) */
    { number: 89, symbol: "Ac", name: "Actinium", category: "actinide", col: 3, row: 10, desc: "Radioactive.", uses: "Research.", pros: "Unique.", cons: "Hazard." },
    { number: 90, symbol: "Th", name: "Thorium", category: "actinide", col: 4, row: 10, desc: "Radioactive.", uses: "Nuclear.", pros: "Energy.", cons: "Waste." },
    { number: 91, symbol: "Pa", name: "Protactinium", category: "actinide", col: 5, row: 10, desc: "Rare.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 92, symbol: "U", name: "Uranium", category: "actinide", col: 6, row: 10, desc: "Radioactive.", uses: "Fuel.", pros: "Energy.", cons: "Waste." },
    { number: 93, symbol: "Np", name: "Neptunium", category: "actinide", col: 7, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 94, symbol: "Pu", name: "Plutonium", category: "actinide", col: 8, row: 10, desc: "Radioactive.", uses: "Fuel.", pros: "Energy.", cons: "Hazard." },
    { number: 95, symbol: "Am", name: "Americium", category: "actinide", col: 9, row: 10, desc: "Radioactive.", uses: "Detectors.", pros: "Useful.", cons: "Hazard." },
    { number: 96, symbol: "Cm", name: "Curium", category: "actinide", col: 10, row: 10, desc: "Radioactive.", uses: "Research.", pros: "Unique.", cons: "Hazard." },
    { number: 97, symbol: "Bk", name: "Berkelium", category: "actinide", col: 11, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 98, symbol: "Cf", name: "Californium", category: "actinide", col: 12, row: 10, desc: "Radioactive.", uses: "Neutron source.", pros: "Useful.", cons: "Hazard." },
    { number: 99, symbol: "Es", name: "Einsteinium", category: "actinide", col: 13, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 100, symbol: "Fm", name: "Fermium", category: "actinide", col: 14, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 101, symbol: "Md", name: "Mendelevium", category: "actinide", col: 15, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 102, symbol: "No", name: "Nobelium", category: "actinide", col: 16, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },
    { number: 103, symbol: "Lr", name: "Lawrencium", category: "actinide", col: 17, row: 10, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Radioactive." },

    { number: 104, symbol: "Rf", name: "Rutherfordium", category: "transition metal", col: 4, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 105, symbol: "Db", name: "Dubnium", category: "transition metal", col: 5, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 106, symbol: "Sg", name: "Seaborgium", category: "transition metal", col: 6, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 107, symbol: "Bh", name: "Bohrium", category: "transition metal", col: 7, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 108, symbol: "Hs", name: "Hassium", category: "transition metal", col: 8, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 109, symbol: "Mt", name: "Meitnerium", category: "transition metal", col: 9, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 110, symbol: "Ds", name: "Darmstadtium", category: "transition metal", col: 10, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 111, symbol: "Rg", name: "Roentgenium", category: "transition metal", col: 11, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 112, symbol: "Cn", name: "Copernicium", category: "transition metal", col: 12, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 113, symbol: "Nh", name: "Nihonium", category: "post-transition metal", col: 13, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 114, symbol: "Fl", name: "Flerovium", category: "post-transition metal", col: 14, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 115, symbol: "Mc", name: "Moscovium", category: "post-transition metal", col: 15, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 116, symbol: "Lv", name: "Livermorium", category: "post-transition metal", col: 16, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 117, symbol: "Ts", name: "Tennessine", category: "halogen", col: 17, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." },
    { number: 118, symbol: "Og", name: "Oganesson", category: "noble gas", col: 18, row: 7, desc: "Synthetic.", uses: "Research.", pros: "Unique.", cons: "Short-lived." }
];